services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: Discord_clone
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'